### ISSUE TITLE
Domain down samp-udf.net

### ISSUE THREAD

**Issue by axi92** [Suchty112/SAMP-UDF-for-AutoHotKey#5]
Wurde das Programm aufgelassen?

**Comment by Suchty112** [comment]
Nein wurde es nicht, das Forum sowie Wiki war die ganze zeit weiterhin erreichbar, nur die hauptdomain ist umgezogen und ich hatte noch keine Zeit gehabt aufgrund privater Sachen dieses wieder hochzuladen auf den server :). wird aber grad gemacht :)
