### ISSUE TITLE
VehicleSpeed

### ISSUE THREAD

**Issue by irobin591** [Suchty112/SAMP-UDF-for-AutoHotKey#7]
Ist es möglich, irgendwie die Geschwindigkeit eines Autos o.ä. auszulesen oder geht das mit den neueren Versionen nicht?

**Comment by Suchty112** [comment]
Ich hab was gefunden, muss aber erst selber testen die Tage ob dieses nur für die R1 ist oder für R2 (Sieht man dann ja am Crash xD)

**Comment by Suchty112** [comment]
Ist unter https://github.com/SAMP-UDF/SAMP-UDF-for-Autohotkey seit ca 14 Tagen drinne :)
