### ISSUE TITLE
Parameter Fehler

### ISSUE THREAD

**Issue by Sigigamer** [Suchty112/SAMP-UDF-for-AutoHotKey#9]
Hab damals mit der API.ahk Keybinder für SAMP gemacht und wollte das ganze jetzt mit der SAMP.ahk ebenfalls versuchen. Wenn ich die Funktionen wie gewohnt anwenden möchte, erhalte ich dummerweise einen Parameterfehler. Damit man sich jetzt ein Bild machen kann, was ich meine, habe ich hier folgendes Beispiel:

Numpad0::
If (isInChat())
{
Send 0
}
else
{
Send t
sleep 30
Send Ich bin 
}
return

Numpad1::
If (isInChat())
{
Send 1
}
else
{
getUsername(Test)                **Zeile 59**
Send t
Sleep 30
Send %Test%
}
return

Fehlercode C:\Users\User\Desktop\Tools\Autohotkey\SAMP\Testkacke\Testscript.ahk (59) : ==> Too many parameters passed to function.
 Specifically: getUsername(Test)
>Exit code: 2    Time: 0.0746

Nach vielen Stunden suchen finde ich den Fehler nicht, also gehe ich davon aus, dass ich die SAMP.ahk falsch benutze. Includet ist die ahk und die IsInChat funktion, funktioniert wunderbar, nur Werteabfragen, wie Name, HP, ID.... mlchten bei mir auf diese Art und weise nicht funktionieren. 

Lösungsansätze?

**Comment by Marionaise** [comment]
Änder mal bitte
`getUsername(Test)`
in
`getUsername("Test")`

**Comment by Cireyses** [comment]
Hallo, @Sigigamer.
Es ist zwar schon etwas her, aber vielleicht hast du, oder auch Andere immer noch das Problem.
Die Funktion `getUsername()` benötigt keine Parameter, da die Funktion den Namen direkt zurückgibt und nicht erst über ein Referenzparameter. Im Grunde kannst du wie gewohnt eine Variable mit der Funktion zuweisen: `Test := getUsername()` oder einfach direkt die Funktion in deinem Text anwenden.

Gruß.

Siehe Beispiel in der Datei [https://github.com/Suchty112/SAMP-UDF-for-AutoHotKey/blob/master/SAMPTest.ahk](url) - Zeile 81.
